# Basic config stuff
[config]
# Max rate in Mbps
link_capacity = 600

# Choice of dynamic allocation algorithm
# 0 - None
# 1 - egalitarian fairness
# 2 - proportial fairness
# 3 - hybrid proportional fairness
algorithm = 1

# --- Main switch ---
[[switches]]
dpid = 1

# --- main switch queues ---

    # bash script to install queues
    [switches.queues]
    queue_script = "./mininet/mn_dummy_queues.sh"
    clear_queue_script = "./mininet/mn_dummy_clear_queues.sh"

# --- main switch meters ---

    # meter 1
    [[switches.meters]]
    dpid = 1
    flags = ["KBPS"]
    meter_id = 1

        [[switches.meters.bands]]
        type = "DSCP_REMARK"
	    prec_level = 10
        rate = 100000

    # meter 2
    [[switches.meters]]
    dpid = 1
    flags = ["KBPS"]
    meter_id = 2

        [[switches.meters.bands]]
        type = "DSCP_REMARK"
	    prec_level = 10
        rate = 200000


# --- main switch flows ---

    # --- static flows (installed and then left untouched by the controller) ---

    # ARP flow
    [[switches.static_flows]]
    dpid = 1
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0

        [switches.static_flows.match]
        eth_type = 2054

        [[switches.static_flows.actions]]
        type = "OUTPUT"
        port = "FLOOD"

    # H3H1 flow
    [[switches.static_flows]]
    dpid = 1
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0

        [switches.static_flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.3"
        ipv4_dst = "10.0.0.1"

        [[switches.static_flows.actions]]
        type = "OUTPUT"
        port = 1

    # H3H2 flow
    [[switches.static_flows]]
    dpid = 1
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0

        [switches.static_flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.3"
        ipv4_dst = "10.0.0.2"

        [[switches.static_flows.actions]]
        type = "OUTPUT"
        port = 2

    # --- main flows (controller will calculate the bandwidth for these) ---

    # H1H3 flow
    [[switches.flows]]
    dpid = 1
    cookie = 1
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 100

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.1"
        ipv4_dst = "10.0.0.3"

        [[switches.flows.actions]]
        type = "METER"
        meter_id = 1

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 3

    # H2H3 flow
    [[switches.flows]]
    dpid = 1
    cookie = 2
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 100

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.2"
        ipv4_dst = "10.0.0.3"

        [[switches.flows.actions]]
        type = "METER"
        meter_id = 2

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 3


# --- tier 2 switch ---
[[switches]]
dpid = 2

# --- tier 2 switch queues ---

    # bash script to install queues
    [switches.queues]
    queue_script = "./mininet/mn_dummy_queues.sh"
    clear_queue_script = "./mininet/mn_dummy_clear_queues.sh"

# --- tier 2 switch meters (for remarked traffic) ---

    # meter 1
    [[switches.meters]]
    dpid = 2
    flags = ["KBPS"]
    meter_id = 1

        [[switches.meters.bands]]
        type = "DSCP_REMARK"
	    prec_level = 12
        rate = 1000

    # meter 2
    [[switches.meters]]
    dpid = 2
    flags = ["KBPS"]
    meter_id = 2

        [[switches.meters.bands]]
        type = "DSCP_REMARK"
	    prec_level = 12
        rate = 1000


# --- tier 2 switch flows ---

    # --- static flows (installed and then left untouched by the controller) ---

    # ARP flow
    [[switches.static_flows]]
    dpid = 2
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0

        [switches.static_flows.match]
        eth_type = 2054

        [[switches.static_flows.actions]]
        type = "OUTPUT"
        port = "FLOOD"

    # H3H1 flow
    [[switches.static_flows]]
    dpid = 2
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0

        [switches.static_flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.3"
        ipv4_dst = "10.0.0.1"

        [[switches.static_flows.actions]]
        type = "OUTPUT"
        port = 1

    # H3H2 flow
    [[switches.static_flows]]
    dpid = 2
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0

        [switches.static_flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.3"
        ipv4_dst = "10.0.0.2"

        [[switches.static_flows.actions]]
        type = "OUTPUT"
        port = 1

    # --- main flows (controller will calculate the bandwidth for these) ---

    # --- high priority flows ---
    # H1H3 flow - high priority
    [[switches.flows]]
    dpid = 2
    cookie = 10
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 100

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.1"
        ipv4_dst = "10.0.0.3"

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 2

    # H2H3 flow - high priority
    [[switches.flows]]
    dpid = 2
    cookie = 11
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 100

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.2"
        ipv4_dst = "10.0.0.3"

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 2

    # --- remarked flows (DSCP 10)---
    # H1H3 flow - remarked
    [[switches.flows]]
    dpid = 2
    cookie = 1
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 200

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.1"
        ipv4_dst = "10.0.0.3"
        ip_dscp = 10

        [[switches.flows.actions]]
        type = "METER"
        meter_id = 1

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 2

    # H2H3 flow - remarked
    [[switches.flows]]
    dpid = 2
    cookie = 2
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 200

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.2"
        ipv4_dst = "10.0.0.3"
        ip_dscp = 10

        [[switches.flows.actions]]
        type = "METER"
        meter_id = 2

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 2


# --- tier 3 switch ---
[[switches]]
dpid = 3

# --- tier 3 switch queues ---

    # bash script to install queues
    [switches.queues]
    queue_script = "./mininet/mn_s3_queues.sh"
    clear_queue_script = "./mininet/mn_s3_clear_queues.sh"

# --- tier 3 switch meters ---

    # meter 1 - actually unused
    [[switches.meters]]
    dpid = 3
    flags = ["KBPS"]
    meter_id = 1

        [[switches.meters.bands]]
        type = "DROP"
        rate = 300000


# --- tier 3 switch flows ---

    # --- static flows (installed and then left untouched by the controller) ---

    # ARP flow
    [[switches.static_flows]]
    dpid = 3
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0

        [switches.static_flows.match]
        eth_type = 2054

        [[switches.static_flows.actions]]
        type = "OUTPUT"
        port = "FLOOD"

    # H3H1 flow
    [[switches.static_flows]]
    dpid = 3
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0

        [switches.static_flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.3"
        ipv4_dst = "10.0.0.1"

        [[switches.static_flows.actions]]
        type = "OUTPUT"
        port = 1

    # H3H2 flow
    [[switches.static_flows]]
    dpid = 3
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0

        [switches.static_flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.3"
        ipv4_dst = "10.0.0.2"

        [[switches.static_flows.actions]]
        type = "OUTPUT"
        port = 1

    # --- main flows (controller will calculate the bandwidth for these) ---

    # --- high priority flows (no DSCP) ---
    # H1H3 flow - high priority
    [[switches.flows]]
    dpid = 3
    cookie = 3
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 100

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.1"
        ipv4_dst = "10.0.0.3"

        [[switches.flows.actions]]
        type = "SET_QUEUE"
        queue_id = 2

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 2

    # H2H3 flow - high priority
    [[switches.flows]]
    dpid = 3
    cookie = 4
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 100

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.2"
        ipv4_dst = "10.0.0.3"

        [[switches.flows.actions]]
        type = "SET_QUEUE"
        queue_id = 2

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 2

    #--- medium priority flows (DSCP 10) ---
    # H1H3 flow - medium priority
    [[switches.flows]]
    dpid = 3
    cookie = 5
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 200

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.1"
        ipv4_dst = "10.0.0.3"
        ip_dscp = 10

        [[switches.flows.actions]]
        type = "SET_QUEUE"
        queue_id = 1

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 2

    # H2H3 flow - medium priority
    [[switches.flows]]
    dpid = 3
    cookie = 6
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 200

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.2"
        ipv4_dst = "10.0.0.3"
        ip_dscp = 10

        [[switches.flows.actions]]
        type = "SET_QUEUE"
        queue_id = 1

        [[switches.flows.actions]]
        type = "OUTPUT"
        port = 2

    #--- low priority flows (DSCP 12) ---
    # H1H3 flow - low priority
    [[switches.flows]]
    dpid = 3
    cookie = 7
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 300

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.1"
        ipv4_dst = "10.0.0.3"
        ip_dscp = 12

        # Enable this action for implicit drop
        [[switches.flows.actions]]
        type = "CLEAR_ACTIONS"

        # Enable these actions for overflow support
        # [[switches.flows.actions]]
        # type = "SET_QUEUE"
        # queue_id = 0

        # [[switches.flows.actions]]
        # type = "OUTPUT"
        # port = 2

    # H2H3 flow - low priority
    [[switches.flows]]
    dpid = 3
    cookie = 8
    table_id = 0
    idle_timeout = 0
    hard_timeout = 0
    priority = 300

        [switches.flows.match]
        eth_type = 2048
        ipv4_src = "10.0.0.2"
        ipv4_dst = "10.0.0.3"
        ip_dscp = 12

        # Enable this action for implicit drop
        [[switches.flows.actions]]
        type = "CLEAR_ACTIONS"

        # Enable these actions for overflow support
        # [[switches.flows.actions]]
        # type = "SET_QUEUE"
        # queue_id = 0

        # [[switches.flows.actions]]
        # type = "OUTPUT"
        # port = 2